docker-registry-manager:
  build: .  # build the checked out version in the current working directory
  container_name: docker-registry-manager
  environment:
    - VERBOSITY=5   # Log level of 6 is debug mode. See main.go init for log level details
    - REGISTRY=
  ports:
    - 8080:8080
    - 8088:8088
